# #Program 1: Print Even Numbers from 10 to 100
# for i in range(10, 101):
#     if i % 2 == 0:
#         print(i)




# # ---------------------------------------------------------------------------------------------------------------------        

# # Program 2: Print Even Numbers Using Function



# def print_even_number(start, end):
#     for i in range(start, end):
#         if i % 2 == 0:
#             print(i)

# print_even_number(10, 21)


# # ---------------------------------------------------------------------------------------------------------------------        
# # This function prints even numbers between the given start and end values.

# # Program 3: Simple Sum Function
# def summ(a, b):
#     print(a + b)

# summ(99, 3)

# # ---------------------------------------------------------------------------------------------------------------------        

# # Program 4: Create a List Using Input Function
# # 👉 Input: 10, 20, 33, 44, 55
 
# my_listt = []

# for i in range(5):
#     elements = int(input("enter the elements: "))
#     my_listt.append(elements)
#     print(my_listt)

# # ---------------------------------------------------------------------------------------------------------------------        


# # Program 5: Store Friends Name Using Function
# def print_my_friends_name():
#     my_friend_list = []

#     for i in range(4):
#         friends = input("enter your friends name: ")
#         my_friend_list.append(friends)
#         print(my_friend_list)

# print_my_friends_name()
