# For Loop with range()
# for i in range(5):
#     print(i)

# for i in range(0,5):
#     print(i)



# my_listt = ["Ravi", "rohit", 44, 55, 88]
# print(my_listt)

# for i in my_listt:
#     print(i)


# # break Example (Range Loop)
# for i in range(0, 12):
#     if i == 7:
#         break
#     print(i)

# # Continue Example (Range Loop)
# for i in range(0, 12):
#     if i == 7:
#         continue
#     print(i)


