# ------------- JavaScript Language --------------------------
# console.log("Ansh Thakur!");
# // javascript programming language

# ----------- Python Language ----------------------------
# print("Ansh Thakur!")
# # python programming language

# ------------------ C Language ---------------------
# #include <stdio.h>

# int main()
# {
#     printf("Ansh Thakur");

#     return 0;
# }

# ---------------Java Language ----------
# public class Main
# {
# 	public static void main(String[] args) {
# 		System.out.println("ANsh Thakur ");
# 	}
# }
# print("Ansh Thakur!")
# print("Sonu")
# print("Ujwal")
# print("Ravi")
# print("NIraj")
# print("Ajit")
# print("Deewakar")
# print("ANuj")
# print("Aditya")
# print("kaajal")
# -----------------------how to print list-------------------------------------------------
list = []
n = int (input("enter number of list"))
for i in range (n):
      number =int(input("enter your number"))
      list.append(number)
      print(list)
      