# # String Concatenation ("+") :-  => it joins two strings
# first_name = "Sonu" 
# last_name= "xyz"
# full_name = first_name + ' ' + last_name
# print(full_name)

# # String Replication ("*"):- it is used to repeate any strings multiple time. 

# first_name = "Sonu"
# last_name= "xyz"
# full_name = first_name + ' ' + last_name
# print(first_name)
# print(full_name)
# print(full_name*6) #<-String Replication
# name = "Ravi"
# print(name*70)   #<-String Replication
