# --------------------------------------------I N S E R T ----------------------------------------------------------------------

# my_list = [11, 22, 33, 44]
# print("Before:", my_list)

# my_list.insert(2, 999)   # Inserts 999 at index 2
# my_list.insert(46, 11110)   # Inserts 999 at index 2
# print("After:", my_list)

# --------------------------------------------R E M O V E  ----------------------------------------------------------------------


# my_list = [11, 22, 22, 33, 44]
# print("Before:", my_list)

# my_list.remove(22)
# print("After:", my_list)
# my_list.insert(4,4444)
# print(my_list)

# --------------------------------------------P O P ----------------------------------------------------------------------

# my_list = [11, 22, 24, 33, 44]
# print("Before:", my_list)

# my_list.pop(1)   # Removes element at index 1
# my_list.pop(3)   # Removes element at index 1
# print("After:", my_list)

# my_list = [11, 22, 24, 33, 44, 100, 1000, 100]
# print("Index of 24:", my_list.index(24))
# print("Index of 24:", my_list.index(22))

# -------------------------------------------- C O U N T ----------------------------------------------------------------------

# my_list = [11, 22, 24, 33, 44, 100, 1000, 100]
# print("Count of 100:", my_list.count(100))

# my_list=[1,1,1,2,2,2,3,3,3,3,3,4,4,4,4,5,5,5,5,5,]
# print("count of 2:",my_list.count(2))

# -------------------------------------------- S O R T ----------------------------------------------------------------------

# my_list = [11, 22, 24, 33, 44, 100, 1000, 100, 77]
# print("Before:", my_list)

# my_list.sort()
# print("After:", my_list)

# --------------------------------------------R E V E E S E ----------------------------------------------------------------------

# my_list = [11, 22, 24, 33, 44, 100, 1000, 100, 77]
# print("Before:", my_list)

# my_list.reverse()
# print("After:", my_list)

# -------------------------------------------- C O P Y ----------------------------------------------------------------------

# my_list = [11, 22, 24, 33, 44, 100, 1000, 100, 77]
# copied_list = my_list.copy()

# print("Copied list:", copied_list)

# -------------------------------------------- C L E A R ----------------------------------------------------------------------

# my_list = [11, 22, 24, 33, 44, 100, 1000, 100, 77]
# copied_list = my_list.copy()

# print("Copied list:", copied_list)
# print("Before:", my_list)

# my_list.clear()
# print("After:", my_list)
