# # 0 1 2 3 4 5 6 7 8 9 10
# # P r o g r a m m i n g

# language = "Programming"
# print(language[2:9])

# print(language[0: ]) 
# print(language[ : ])
# print(language[ 4: -1])

# 0 1 2 3 4 5 6 7 8 9 10
# P r o g r a m m i n g

#   P       r     o     g      r     a     m    m     i      n      g
# -11    -10  -9    -8    -7    -6    -5    -4    -3    -2     -1
# language="programming"

# print(language[-8: ])


##Slicing: Three parameters

# language = "Programming"
# print("with gap the output is", language[0:7:1])
# print("without gap the output is ", language[0:7])

# language2 = "javascript"
# print(language2[0:9:2])


# language = "Programming"
# print(language)
# print(language[9])
# print(language[8])
# print(language[-2])
# print(language[-6])
# print(language[0:8])  #e r a m m
# print(language[2:9])  # o g r a m m i
# print(language[0: ])  # P r o g r a m m i n g
# print(language[ : ])  # P r o g r a m m i n g
# print(language[ 4: -1])  # r a m m i n
# print(language[-8: ])  # g   r   a   m   m   i   n    g

# print("with gap the output is", language[0:7:1])
# print("without gap the output is ", language[0:7])
